### ISSUE TITLE
DATASET FOR BREAST CANCER IMAGE ANALYSIS_URGENT

### ISSUE THREAD

**Issue by bplm** [void-mckenzie/BreaKHis_Image_Analysis#1]
Hi @void-mckenzie 
I am unable to understand that there is no data in the data folder and when I try to download in to my google colab using the link that is there , it shhows this error
PatoolError: patool can not unpack
ERROR: /content/data.zip
/content/data.zip
Open ERROR: Can not open the file as [zip] archive

ERRORS:
Is not archive
patool error: error extracting /content/data.zip: Command `['/usr/bin/7z', 'x', '-y', '-o/content', '--', '/content/data.zip']' returned non-zero exit status 2

PLEASE HELP SORT THIS OUT

**Comment by void-mckenzie** [comment]
I know it has been 4 years, but man, the readme asks you to unzip the dataset and delete the readme. Use the proper unzipping software, or unzip in windows and upload. it.
